// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quozvgcsuhpsojqftume.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1b3p2Z2NzdWhwc29qcWZ0dW1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5Mjk3NzQsImV4cCI6MjA1NjUwNTc3NH0.qQrIJ3zv543H-04VOoqXzmK4RfjIkHGiEpoMSx_BWIQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);